version: '3.9'

networks:
  graphql-network:
    driver: bridge

services:
  app:
    build:
      context: ./app
      args:
        UID: $UID
        GID: $GID
    ports:
      - "80:16761"
      - "2345:2345"
    volumes:
      - ./$PROJECT_PATH:/var/graphql
      - $OPERA_IPC_PATH:/app/opera.ipc
    environment:
      - START_APP=$START_APP
      - CFG_PATH=$CONTAINER_CFG_PATH
    security_opt:
      - "seccomp:unconfined"
    networks:
      - graphql-network

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PW
    networks:
      - graphql-network